doc-warnings: yes
test-warnings: no
strictness: veryhigh
max-line-length: 80

pep8:
    full: true

autodetect: yes

requirements:
    - deps/core.txt
    - deps/test.txt

ignore-paths:
    - doc
    - example
    - src/ltpkgbuilder_data

ignore-patterns:
    - ^example/doc_.*\.py$
    - (^|/)docs(/|$)